qilimanjaro-tech/qililab

- docs/releases/changelog-dev.md
- src/qililab/execute_circuit.py
- tests/test_execute_circuit.py
This PR improves the `ql.execute` function, adding the functionality of executing multiple circuits without having to connect/disconnect to the instruments.
> Improve the execute function.

- docs/releases/changelog-dev.md
- examples/runcards/galadriel.yml
- src/qililab/execute_circuit.py
- src/qililab/settings/gate_event_settings.py
- src/qililab/transpiler/gate_decompositions.py
- src/qililab/transpiler/transpiler.py
- tests/settings/test_gate_settings.py
- tests/transpiler/test_transpiler.py
- Changed default value for optimize in translate_circuit from `False -> True`
- Add CZ gate phase correction from tomography calibration as virtual z gate
> Cphase phase correction

- src/qililab/pulse/pulse_shape/cosine.py
- src/qililab/pulse/pulse_shape/drag.py
- src/qililab/pulse/pulse_shape/gaussian.py
- src/qililab/pulse/pulse_shape/pulse_shape.py
- src/qililab/pulse/pulse_shape/rectangular.py
- src/qililab/pulse/pulse_shape/snz.py
- src/qililab/waveforms/__init__.py
- src/qililab/waveforms/arbitrary.py
- src/qililab/waveforms/drag.py
- src/qililab/waveforms/drag_correction.py
- src/qililab/waveforms/gaussian.py
- src/qililab/waveforms/iq_pair.py
- src/qililab/waveforms/square.py
- src/qililab/waveforms/waveform.py
Improvement on `Waveforms` documentation for the selection process.
During which I did some improvement to the pulse_shape documentation as well.
> docs_improvements_for_Waveforms&PulseShapes

- src/qililab/data_management.py
- tests/platform/test_platform.py
PR solving a deprecation in qililab
> Change ruamel.yaml.dump deprecated

- src/qililab/circuit/circuit.py
- src/qililab/drivers/instruments/keithley/keithley_2600.py
- src/qililab/drivers/instruments/qblox/cluster.py
- src/qililab/drivers/instruments/qblox/pulsar.py
- src/qililab/drivers/instruments/qblox/sequencer_qcm.py
- src/qililab/drivers/instruments/qblox/sequencer_qrm.py
- src/qililab/drivers/instruments/qblox/spi_rack.py
- src/qililab/drivers/instruments/yokogawa/yokogawa_gs200.py
- src/qililab/execution/execution_manager.py
- src/qililab/instruments/instrument.py
- src/qililab/platform/components/bus_driver.py
- src/qililab/platform/components/drive_bus.py
- src/qililab/platform/components/flux_bus.py
- src/qililab/platform/components/readout_bus.py
- src/qililab/transpiler/native_gates.py
- src/qililab/waveforms/arbitrary.py
- src/qililab/waveforms/drag.py
- src/qililab/waveforms/drag_correction.py
- src/qililab/waveforms/gaussian.py
- src/qililab/waveforms/square.py
PR moving/deleteing the docstrings from _init_ to class level docstrings, since that's what we decided.
> delete _init_() docstrings!

- docs/releases/changelog-dev.md
- src/qililab/instruments/qblox/qblox_qrm.py
- tests/instruments/qblox/test_qblox_qrm.py
> fix for residual acquisitions

- docs/releases/changelog-dev.md
- src/qililab/typings/enums.py
i guess you may need to add some tests. It's just two new parameters for the SNZ gate
> add a couple new enums for SNZ gate

- docs/releases/changelog-dev.md
- src/qililab/platform/platform.py
- tests/platform/test_platform.py
> Check that circuit execution time is shorter than `repetition_duration`

- CHANGELOG.md
- docs/releases/changelog-dev.md
- src/qililab/config/version.py
This branch brings the latest changes for release 0.22.0 of the Qililab library.
> Release 0.22.0

- CHANGELOG.md
- src/qililab/config/version.py
This release brings a hotfix to the bug where Intermediate Frequency cannot be read or set for the RF modules.
> new release 0.22.1

- CHANGELOG.md
- docs/releases/changelog-dev.md
- src/qililab/config/version.py
This branch brings a new release for Qililab with latest changes, motivated by the fix of the bug https://github.com/qilimanjaro-tech/qililab/issues/644
> new release PR

- docs/getting_started/installation.rst
This branch brings a bare minimum of Qililab installation instructions for the regular users (not development users)
> minimum installation instructions

- CHANGELOG.md
- docs/releases/changelog-dev.md
- src/qililab/config/version.py
This branch brings the new release for Qililab.
> Release 0 25 0

- docs/releases/changelog-dev.md
- src/qililab/pulse/pulse_shape/flat_top.py
- src/qililab/pulse/qblox_compiler.py
- tests/pulse/pulse_shape/test_flat_top.py
- tests/pulse/test_qblox_compiler.py
This hotfix brings manually hardcoded time of flight as implemented by Paul and his latest changes in the Flat Top pulse shape.
> hotfixes to add TOF and new flat_top changes

- src/qililab/qprogram/quantum_machines_compiler.py
This is a temporal Hotfix with the bugfix, some feedback is required from Hardware to see if this is the real solution
Bug reference: https://github.com/qilimanjaro-tech/qililab/issues/709
> [BUG] hotfix to prevent the bug, now the duration is considered while defining the hashtag of the waveform

- CHANGELOG.md
- docs/releases/changelog-dev.md
- src/qililab/config/version.py
This PR brings the new release 0.26.2 which removes some unused qiboconnection functionality plus bringing a new waveform.
> release 0.26.2

- docs/releases/changelog-dev.md
- src/qililab/platform/platform.py
- src/qililab/qprogram/qblox_compiler.py
- tests/qprogram/test_qblox_compiler.py
> [QHC-262] Add measure method for qprogram qblox

- src/qililab/instruments/quantum_machines/quantum_machines_cluster.py
When the elements are set in mix_inputs and we do a set_parameter for the IF the mixers if_frequency do not update correctly and couses a crash from qm side
> adding mixers when doing set_parameter

- CHANGELOG.md
- docs/fundamentals/qprogram.rst
- docs/index.rst
- src/qililab/__init__.py
- src/qililab/calibration/__init__.py
- src/qililab/calibration/calibration_node.py
- src/qililab/qprogram/__init__.py
- src/qililab/result/__init__.py
- src/qililab/result/result.py
- src/qililab/result/results.py
> Solve documentation issues for [qhc-619]

- src/qililab/platform/platform.py
> [QHC-666] Execute qprogram docstring

- docs/releases/changelog-dev.md
- Until line 140 its automatic formater changes
- Missing changelog for https://github.com/qilimanjaro-tech/qililab/pull/746
(Really only ✏️ +10-0 lines changed)
> Changelog for cleaning calibration

- src/qililab/qprogram/quantum_machines_compiler.py
- tests/qprogram/test_quantum_machines_compiler.py
Fixes https://linear.app/qilimanjaro/issue/QHC-703/qm-creates-same-hash-for-different-arbitrary-waveforms
> [QHC-703]Hash waveform hotfix

- src/qililab/instruments/quantum_machines/quantum_machines_cluster.py
Fixed bug for set parameter IF in QM.
I didn't add changelog for the bug as inside the changelog there is already a change inside bug fixes explaining this issue (PR 764)
> fixed bug IF

- docs/releases/changelog-dev.md
- src/qililab/instruments/quantum_machines/quantum_machines_cluster.py
- src/qililab/platform/components/bus.py
- tests/data.py
- tests/instruments/quantum_machines/test_quantum_machines_cluster.py
I also added a bugfix after the major runcard changes involving set and get paremeters for QM
> added timeout and modified set and get for qm

- docs/releases/changelog-dev.md
- src/qililab/slurm.py
- tests/test_slurm.py
https://linear.app/qilimanjaro/issue/CLO-849/install-slurm-in-sauron-and-give-support-1q-and-2q-in-qinu
> modify magic method + unit tests

- docs/releases/changelog-dev.md
- src/qililab/instruments/quantum_machines/quantum_machines_cluster.py
- tests/instruments/quantum_machines/test_quantum_machines_cluster.py
added optional parameter inside the runcard
> Add shareable inside qm controllers

- docs/releases/changelog-dev.md
- src/qililab/platform/platform.py
This PR brings a fix in a typo for buses aliases.
> bus_alias typo

- CHANGELOG.md
- docs/releases/changelog-dev.md
- src/qililab/config/version.py
This PR brings release 0.29.0 of Qililab.
> Release changes

- CHANGELOG.md
- docs/releases/changelog-dev.md
- setup.py
This PR is a fix to a previously failed release 0.29.1
> changes for new release

- pyproject.toml
This PR tries to update the build wheels setup version to ensure we build with one of the allowed metadata version
> building wheels

- CHANGELOG.md
- docs/releases/changelog-dev.md
- src/qililab/config/version.py
This PR brings the necessary changes for release 0.29.2
> for the release

- docs/releases/changelog-dev.md
- src/qililab/platform/platform.py
- src/qililab/qprogram/experiment_executor.py
- src/qililab/result/database.py
- src/qililab/result/experiment_results_writer.py
- src/qililab/result/stream_results.py
- tests/platform/test_platform.py
- tests/qprogram/test_experiment_executor.py
- tests/result/test_database.py
- tests/result/test_stream_results.py
Implemented new parameters inside the db_manager config file to distinguish between local and shared base paths
> [QHC-1000]Added distinction between local and shared files in config file

- docs/releases/changelog-dev.md
- src/qililab/result/database.py
- src/qililab/result/result_management.py
- tests/result/test_database.py
- tests/result/test_result_management.py
Small fix for liveplot to work propperly
> Quick fix liveplot load
