src/qililab/pulse/circuit_to_pulses.py, tests/pulse/test_circuit_to_pulses.py
For some unknown reason gates with negative amplitudes are not working properly with Qblox.
A workaround we can take is, when transpiling gates into pulses, add `np.pi` to the phase if the amplitude is negative.
=> Fix gates with negative amplitudes

src/qililab/system_control/system_control.py, tests/pulse/test_circuit_to_pulses.py, tests/system_controls/test_system_control.py
This PR fixes a bug where, if the user added an instrument alias inside a system control that was not present in the platform, no error was raised and no instrument was added in the bus.
```yaml
- alias: drive_line_q4_bus
system_control:
name: system_control
instruments: [Unknown-alias]
port: drive_line_q4
distortions: []
```
Now an error is raised to make sure the user knows that the alias of the instrument doesn't exist.
=> fix: :bug: Raise error if the alias of an instrument (in SystemControl) is not found in platform.

docs/fundamentals/platform.rst, src/qililab/platform/platform.py
CONTEXT:
The sizes of the for loops before are 11, so the results, even though they are still invented, should be 11 as well for consistency!
=> Platform docs / solving errors of list sizes

src/qililab/slurm.py, tests/test_slurm.py
- when logs folder size limit is reached, ensure that the oldest job files are deleted (age defined by job id). There might have been some cases where log files from recent jobs were deleted and hence the error appeared
- raise the size limit of the logs folder to 100 jobs (=500 files). This should avoid deleting logs from most recent jobs and hence prevent the error from appearing although several jobs are submitted in a short time-frame (that's the case of autocalibration, if i'm not mistaken)
=> Fix slurm magic method

src/qililab/slurm.py, tests/test_slurm.py
See below that jobs 969 to 973 have been queued with low priority with -`lp true` and 974 has priority != 0. Hence, 974 is executed first  despite it was the last to be submitted
```
(qililab) adria@adria-Summit-E16Flip-A12UCT:~/Projects/qililab$ sprio -n
JOBID PARTITION PRIORITY   PARTITION 
969 local     0.00000000 1.0000000 
970 local     0.00000000 1.0000000 
971 local     0.00000000 1.0000000 
972 local     0.00000000 1.0000000 
973 local     0.00000000 1.0000000 
974 local     0.00000023 1.0000000 
(qililab) adria@adria-Summit-E16Flip-A12UCT:~/Projects/qililab$ squeue
JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
973     local submitit    adria PD       0:00      1 (Priority)
972     local submitit    adria PD       0:00      1 (Priority)
971     local …
```
=> Add low_priority jobs to slurm magic method

src/qililab/qprogram/operations/play.py, src/qililab/qprogram/qblox_compiler.py, src/qililab/qprogram/qprogram.py, tests/qprogram/test_qblox_compiler.py
Since `time_of_flight` is not yet added to runcard settings for Qblox, and measurement is not unified under one operation `measure`, users need a way to define a `time_of_flight` wait time between readout pulse and acquisition. This PR adds this functionality:
```
qp.play(bus="readout_bus", waveform=readout_pair, wait_time=4)
```
=> [DIRTY-FIX] Add `wait_time` to play operation for Qblox

src/qililab/calibration/calibration_controller.py, tests/calibration/test_calibration_controller.py
This PR splits the 1q and 2q tables, and since lot of code was going to be duplicated, I have refactored lot of code in methods, to be called twice, making also the code more readable 🥇 
The final result tables look like this:
=> Split 1q and 2q tables into different dataframes

src/qililab/result/stream_results.py
Quick hotfix to make the __setitem__ requirements match the data of stream_results
=> Hotfix for setitem in stream_results

docs/releases/changelog-dev.md, src/qililab/waveforms/__init__.py, src/qililab/waveforms/drag.py, src/qililab/waveforms/drag_correction.py, src/qililab/waveforms/gaussian.py, tests/qprogram/test_qprogram.py
Added Domain restrictions to `Drag` pulse, `DragCorrection` waveform and `Gaussian` waveform.
=> [QHC-217] Ensure QProgram supports variables in waveforms

.pylintrc, src/qililab/instruments/qblox/qblox_module.py, src/qililab/platform/platform.py, tests/.pylintrc, tests/instruments/qblox/test_qblox_module.py, tests/platform/test_platform.py
Moved the sync outside of upload_qpysequence in Qblox_module into an independent function sync_sequencers located in the same .py file mirroring the function desync_sequencers and added 3 lines in platform.py to also mirror the desync and sync every time the execution is ran.
=> Extracted sync from upload_qpysequence into an independent line

src/qililab/calibration/calibration_controller.py
For less confusions, I putted the order of the parameters and name of them, equal in both cases!
To be merged together with: https://github.com/qilimanjaro-tech/qililab-portfolio/pull/252
=> [QHC-356] Make `platform_parameters` in the notebooks, as in `platform.set_parameters()`

src/qililab/instruments/qblox/qblox_qrm.py, src/qililab/platform/platform.py, tests/platform/test_platform.py
=> Hotfix for the 2readout problem

CHANGELOG.md, src/qililab/config/version.py
This PR brings a release for Qililab including a hotfix necessary to work with two readout buses in the same QRM in the Qblox cluster.
=> changes for release

src/qililab/qprogram/quantum_machines_compiler.py, tests/qprogram/test_quantum_machines_compiler.py
There was a rounding error involving the signs <= and >= in the compilation of the QUA program's for loops, the error caused results not to generate showcasing a bug.
The signs have been replaced by < and > and the stop value has been replaced by stop +- step/2.
This solution has been checked using the experiment located in qililab-portfolio/experiments/qprogram/flux_vs_flux_pulse.ipynb, if the experiment is executed with a gain step number greater than 9 without this hotfix the results will crash and not return anything.
=> Quantum machines 

src/qililab/qprogram/quantum_machines_compiler.py, tests/qprogram/test_quantum_machines_compiler.py
Following the description on the QM reference https://docs.quantum-machines.co/1.1.6/qm-qua-sdk/docs/API_references/qua/dsl_main/#qm.qua._dsl.wait, the used by the QM compiler now is divided by 4 which returns the correct amount of ns waited (before it was multiplied by 4)
=> Qhc 466 bug wait instruction is not compiled proprely on qprogam for

docs/releases/changelog-dev.md, src/qililab/platform/platform.py
qiboconnection_api.block_device() and release_device() is totally redundant since Slurm was integrated in our stack.
As Access is going to remove this functionality from qiboconnection, qililab needs to be updated accordingly.
=> remove release and block device qiboconnection

docs/releases/changelog-dev.md, requirements.txt, src/qililab/__init__.py, src/qililab/platform/platform.py, src/qililab/qprogram/__init__.py, src/qililab/qprogram/calibration.py, src/qililab/qprogram/operations/__init__.py, src/qililab/qprogram/operations/measure.py, src/qililab/qprogram/operations/play.py, src/qililab/qprogram/qblox_compiler.py, src/qililab/qprogram/qprogram.py, src/qililab/qprogram/quantum_machines_compiler.py, src/qililab/waveforms/arbitrary.py, src/qililab/waveforms/drag_correction.py, src/qililab/waveforms/flat_top.py, src/qililab/waveforms/gaussian.py, src/qililab/waveforms/iq_pair.py, src/qililab/waveforms/square.py, src/qililab/waveforms/waveform.py, src/qililab/yaml.py, tests/qprogram/test_calibration.py, tests/qprogram/test_qblox_compiler.py, tests/qprogram/test_qprogram.py, tests/qprogram/test_quantum_machines_compiler.py
- Added `Calibration` class to manage calibrated operations for QProgram, including methods to add (`add_operation`), retrieve (`get_operation`), save (`dump`), and load (`load`) calibration data.
- Introduced `qililab.yaml` namespace that exports a single `YAML` instance for common use throughout qililab. Classes can be registered to this instance with the `@yaml.register_class` decorator.
- Introduced `QProgram.with_bus_mapping` method to remap buses within the QProgram.
- Introduced `QProgram.with_calibration` method to apply calibration to operations within the QProgram.
- Extended `Platform.execute_qprogram` method to accept a calibration instance.
Note: I implemented the calibrated operations only for QProgram's `play` instruction. If we like this implementation it can easily be …
=> [QHC-374] Add Calibration for waveforms, Refactor parts of QProgram

docs/releases/changelog-dev.md, src/qililab/data_management.py, tests/test_data_management.py
Removing deprecated argument (`path` from `build_platform`), we should have deleted, some versions ago already 👌
=> [QHC-543] Remove `path` argument, from `build_platfom()`

src/qililab/circuit_transpiler/gate_decompositions.py, tests/circuit_transpiler/test_gate_decompositions.py
We are adding the translation of the Qibo gate `Align` to a Qililab `Wait`
Note there is no strictly 'wait' gait in Qibo, you can see in the [documentation](https://qibo.science/qibo/stable/api-reference/qibo.html#qibo.gates.Align) (not very well explained 🤠 ) that this gate acts kinda like a barrier and also adds a wait at the end.
=> [QHC-547] Add Align gate to transpiler

src/qililab/waveforms/iq_pair.py, tests/waveforms/test_iq_pair.py
Found a bug on qilitools where an IQPair contained 2 other IQPair (this was a mistake). The error was difficult to trace back because the class IQPair accepted other options beside Waveform without complaining. I added an exception so if you create an IQPair with something other than a Waveform it throws a clear error.
=> Implemented an aditional error on IQPair

docs/index.rst
=> [QHC-669] Add changelog to docs

docs/releases/changelog-dev.md, src/qililab/instruments/quantum_machines/quantum_machines_cluster.py, tests/data.py
Created filters in the controlers section of QUA config
=> added filters on the runcard

docs/releases/changelog-dev.md, requirements.txt, src/qililab/platform/platform.py, tests/platform/test_platform.py
I created a try and except similar to the dataloss error to restart the measurement in case of random timeout issue
=> Temporal fix for QM timeout error

src/qililab/instruments/quantum_machines/quantum_machines_cluster.py, tests/instruments/quantum_machines/test_quantum_machines_cluster.py
Very small PR. Before if you want to set an identifier as a numeric value qm-qua would crash stating that an int/float value cannot be the alias of an element. Now you can set the channel value to anything (i.e readout bus can have channel 1 also in QM, if you set the element correctly)
=> Identifiers for QM are now converted into strings inside cofig file creation

src/qililab/digital/circuit_router.py, src/qililab/digital/circuit_transpiler.py, src/qililab/execute_circuit.py, src/qililab/platform/platform.py
=> Adding info  for `Transpilation`, into ``execute()`` docstring methods

src/qililab/digital/circuit_transpiler.py, src/qililab/execute_circuit.py, src/qililab/platform/platform.py, tests/digital/test_circuit_transpiler.py
Makes `routing` optional & not run by default.
(To run the routing, pass flag `routing=True` manually)
=> [QHC-830] Make `routing` optional & not run by default

docs/releases/changelog-dev.md, src/qililab/qprogram/qblox_compiler.py, tests/qprogram/test_qblox_compiler.py
We have introduced an optimization in the QbloxCompiler that significantly reduces memory usage when compiling square waveforms. The compiler now uses a heuristic algorithm that segments long waveforms into smaller chunks and loops over them. This optimization follows a two-pass search:
1. **First Pass**: The compiler tries to find a chunk duration that divides the total waveform length evenly (i.e., remainder = 0).
1. **Second Pass**: If no exact divisor is found, it looks for a chunk duration that leaves a remainder of at least 4 ns. This leftover chunk is large enough to be stored or handled separately.
Each chunk duration is restricted to the range (\[100, 500\]) ns, ensuring that chunks are neither too small (leading to excessive repetitions) nor too large (risking out-of-memory …
=> [QHC-831] Implement Square Waveform Optmization

src/qililab/calibration/calibration_node.py, src/qililab/data_management.py, src/qililab/instruments/instrument.py, src/qililab/instruments/qblox/qblox_qcm_rf.py, src/qililab/instruments/qblox/qblox_qrm_rf.py, src/qililab/instruments/qdevil/qdevil_qdac2.py, src/qililab/platform/components/bus.py, src/qililab/qprogram/qblox_compiler.py, src/qililab/qprogram/qprogram.py, src/qililab/qprogram/quantum_machines_compiler.py, src/qililab/result/qprogram/quantum_machines_measurement_result.py, src/qililab/settings/digital/digital_compilation_settings.py, src/qililab/settings/digital/gate_event_settings.py, src/qililab/utils/serialization.py
With `cmd + F`, I found a lot of duplicated info in `qililab` regarding `| None` and `optional`, in docstrings mostly.
- Change docstring from `(... | None, optional)` to `(..., optional)`
- Removed Optional in `gate_event_setitngs`
- And some automatic autoformater changes from pre-commit in `qdevil-qdac2.py`
=> Remove duplication of `(... | None, optional)` across `qililab`

src/qililab/platform/platform.py, tests/platform/test_platform.py
Fixed small bug while the Qblox didn't returned anything on the second consecutive experiment run because the cache was not restarted but the Q1ASMs disappear while the Qblox is disconnected
=> reset qpysequence while Qblox disconnects

src/qililab/digital/circuit_optimizer.py, src/qililab/digital/circuit_router.py, src/qililab/digital/circuit_to_pulses.py, src/qililab/digital/circuit_transpiler.py
Changes single to double quotes for inline codes in Sphinx, for some `Transpiler` docs
=> Fix code quotes

docs/releases/changelog-dev.md, src/qililab/config/version.py, src/qililab/slurm.py, tests/test_slurm.py
@JavierSab and @islegmar pointed out that not everyone using `slurm` will have GRES, concretely BSC won't, so this would error...
With this change we will need to release version `0.29.1`, to send BSC, correcting this bug
=> [QHC-924] Remove GRES check in `slurm.py`

.github/workflows/code_quality.yml, .github/workflows/docs.yml, .github/workflows/tests.yml, docs/releases/changelog-dev.md, pyproject.toml, uv.lock
Github Actions now use `pytest-xdist` plugin to run tests in parallel. To run tests in parallel locally use `uv run pytest -n auto --dist loadfile`. The `--dist loadfile` flag is mandatory to avoid conflicts between tests that edit shared data, and should be planned for removal in the future.
=> [QHC-949] Parallelize Tests

pyproject.toml, uv.lock
This PR reverts to the right version for qblox-instruments, which we lost somehow when we introduced uv.
=> Update pyproject.toml for right qblox instruments version

docs/releases/changelog-dev.md, src/qililab/instruments/rohde_schwarz/sgs100a.py, src/qililab/typings/enums.py, tests/instruments/rohde_schwarz/test_rohde_schwarz_sgs100a.py
The R&S SGS100a driver has now the capability to change the operation mode between normal mode and bypass mode. The default mode is the normal mode. The allowed strings for each mode
in the settings are `normal` and `bypass`. If the instrument is reset the native instrument configuration defaults to normal.
=> Modify the SGS100a to include operation mode setting

docs/releases/changelog-dev.md, src/qililab/platform/platform.py, src/qililab/qprogram/qprogram.py
QbloxDraw now supports passing a calibration file as an argument when plotting from both the platform and qprogram.
=> qhc-1071 add calibration file to qbloxdraw

docs/releases/changelog-dev.md, src/qililab/instrument_controllers/qdevil/qdevil_qdac2_controller.py, tests/instrument_controllers/qdevil/test_qdevil_qdac2_controller.py
Now the qcods QDAC2Device instance creates a QDAC2 device with an name depending on the intrumentcontroller's name and alias (just like RS)
=> [QUICKFIX] QDAC2 is now able to use more than one instrument controller

docs/releases/changelog-dev.md, tests/qprogram/test_experiment_executor.py, tests/result/test_database.py
Due to a missing mock on the H5py.File a file was created everytime the tests were run. This has been fixed.
In addition, the assertions for the database have been modified following the rest of the tests code.
=> Fix ExperimentExecutor with databases test creating a file

docs/releases/changelog-dev.md, src/qililab/qprogram/qblox_compiler.py, tests/qprogram/test_qblox_compiler.py
Fixed a bug in the QBlox Compiler handling of the wait, long waits that were a multiple of 65532 (the maximum wait) up to 65535 were giving out an error. This has been solved by checking if the remainder would be below 4. If the remainder is 0 it appends a wait of 65532 and if the remainder is between 1 and 3, the duration of the last wait is computed as : `(INST_MAX_WAIT + remainder) - INST_MIN_WAIT` (where `INST_MAX_WAIT` is 65532 and `INST_MIN_WAIT` is 4) and a wait of `INST_MIN_WAIT` is added.
=> qhc-1115-bug-qblox-wait-from-65532-to-65535-raises-an-error

docs/releases/changelog-dev.md, src/qililab/instruments/qblox/qblox_draw.py, tests/instruments/qblox/test_qblox_draw.py
[BUG] -  When dealing with real time classical time in the qblox draw the real duration was put instead of the wait duration
=> qhc-1111-optimise-q1asm-length

docs/releases/changelog-dev.md, pyproject.toml, uv.lock
Update qblox-instruments to 0.16.0
=> qhc-1061-update-qblox-instruments-to-0160-and-qblox-firmware-to-011

docs/releases/changelog-dev.md, src/qililab/__init__.py, src/qililab/result/__init__.py, src/qililab/result/database.py, tests/result/test_database.py
Added `ql.load_by_id(id)` in qililab, This function allows to retrieve the data path of a measurement with the given id without creating a `DatabaseManager` instance. This function is intended to be used inside notebooks using slurm as `DatabaseManager` cannot be submitted.
=> [QHC 1076] Added external load_by_id for slurm

docs/releases/changelog-dev.md, src/qililab/platform/platform.py, src/qililab/result/qblox_results/qblox_bins_acquisitions.py
Fixed documentation for results `counts`, now it warns the user that instead of `num_avg` they must use `num_bins`.
=> [QUICKFIX] Counts documentation update
